Repository kakao-tech-campus-3rd-step3/Team1_BE, pull requests merged in 2025-09, with the labels that each got.

#17 🐛 base entity 관련 warning
  src/main/java/knu/team1/be/boost/common/entity/BaseEntity.java
  src/main/java/knu/team1/be/boost/file/entity/File.java
Labels: bug

#18 ✨BaseEntity에서 soft delete 필드 분리
  src/main/java/knu/team1/be/boost/common/entity/BaseEntity.java
  src/main/java/knu/team1/be/boost/common/entity/SoftDeletableEntity.java
  src/main/java/knu/team1/be/boost/file/entity/File.java
  src/main/java/knu/team1/be/boost/member/entity/Member.java
  src/main/java/knu/team1/be/boost/task/entity/Task.java
Labels: enhancement

#22 ✨ 파일 Entity @SQLRestriction("deleted = false") 적용
  src/main/java/knu/team1/be/boost/file/entity/File.java
Labels: enhancement

#23 ✨ 파일 API 관련 업로드 용량 제한 추가
  src/main/java/knu/team1/be/boost/common/exception/GlobalExceptionHandler.java
  src/main/java/knu/team1/be/boost/file/exception/FileTooLargeException.java
  src/main/java/knu/team1/be/boost/file/service/FileServiceImpl.java
  src/main/resources/application.yaml
Labels: enhancement

#26 ♻️ Swagger 문서화 관련 컨트롤러 인터페이스 분리
  src/main/java/knu/team1/be/boost/file/controller/FileApi.java
  src/main/java/knu/team1/be/boost/file/controller/FileController.java
  src/main/java/knu/team1/be/boost/member/controller/MemberApi.java
  src/main/java/knu/team1/be/boost/member/controller/MemberController.java
Labels: refactor

#28 ♻️ 파일 API 관련 리팩토링
  src/main/java/knu/team1/be/boost/file/controller/FileApi.java
  src/main/java/knu/team1/be/boost/file/controller/FileController.java
  src/main/java/knu/team1/be/boost/file/dto/FileCompleteRequestDto.java
  src/main/java/knu/team1/be/boost/file/dto/FileCompleteResponseDto.java
  src/main/java/knu/team1/be/boost/file/dto/FileRequestDto.java
  src/main/java/knu/team1/be/boost/file/dto/FileResponseDto.java
  src/main/java/knu/team1/be/boost/file/entity/File.java
  src/main/java/knu/team1/be/boost/file/service/FileService.java
  src/main/java/knu/team1/be/boost/file/service/FileServiceImpl.java
Labels: refactor

#47 🐛 @SQLDelete가 deletedAt 필드를 업데이트 하지 않는 버그 수정
  src/main/java/knu/team1/be/boost/common/entity/SoftDeletableEntity.java
  src/main/java/knu/team1/be/boost/file/entity/File.java
  src/main/java/knu/team1/be/boost/member/entity/Member.java
  src/main/java/knu/team1/be/boost/project/entity/Project.java
  src/main/java/knu/team1/be/boost/projectMember/entity/ProjectMember.java
  src/main/java/knu/team1/be/boost/task/entity/Task.java
Labels: bug

#48 ✨ 할 일 API 구현 (CUD)
  src/main/java/knu/team1/be/boost/common/exception/GlobalExceptionHandler.java
  src/main/java/knu/team1/be/boost/member/exception/MemberNotFoundException.java
  src/main/java/knu/team1/be/boost/task/controller/TaskApi.java
  src/main/java/knu/team1/be/boost/task/controller/TaskController.java
  src/main/java/knu/team1/be/boost/task/dto/TaskCreateRequestDto.java
  src/main/java/knu/team1/be/boost/task/dto/TaskResponseDto.java
  src/main/java/knu/team1/be/boost/task/dto/TaskStatusRequestDto.java
  src/main/java/knu/team1/be/boost/task/dto/TaskUpdateRequestDto.java
  src/main/java/knu/team1/be/boost/task/entity/Task.java
  src/main/java/knu/team1/be/boost/task/entity/TaskStatus.java
  src/main/java/knu/team1/be/boost/task/exception/TaskNotInProjectException.java
  src/main/java/knu/team1/be/boost/task/service/TaskService.java
Labels: enhancement

#54 ✨ 할 일 API 테스트 코드 작성
  src/main/java/knu/team1/be/boost/common/exception/GlobalExceptionHandler.java
  src/test/java/knu/team1/be/boost/file/infra/PresignedUrlFactoryTest.java
  src/test/java/knu/team1/be/boost/task/controller/TaskControllerTest.java
  src/test/java/knu/team1/be/boost/task/service/TaskServiceTest.java
Labels: enhancement
